Repository singnet/language-learning, pull requests merged in 2018-07, with the labels that each got.

#38 Updating and enhancing pre-cleaner
  src/pre-cleaner/README.md
  src/pre-cleaner/cleaner_pipeline.sh
  src/pre-cleaner/msansi2utf8.sh
  src/pre-cleaner/run_cleaner.sh
  src/pre-cleaner/split-sentences.pl
  src/pre-cleaner/tokenizer.py
Labels: enhancement

#42 Documentation Update and Bug Fixes
  LICENSE
  src/cli_scripts/README.md
  src/common/parsemetrics.py
  src/grammar_test/README.md
  src/grammar_test/grammartester.py
  src/grammar_test/textfiledashb.py
  tests/test_grammartester.py
  tests/test_psparse.py
Labels: enhancement

#44 Changes to Grammar Tester
  setup.py
  src/cli_scripts/README.md
  src/cli_scripts/grammar-tester
  src/cli_scripts/parse-evaluator
  src/common/__init__.py
  src/common/cliutils.py
  src/common/dirhelper.py
  src/common/parsemetrics.py
  src/grammar_tester/README.md
  src/grammar_tester/__init__.py
  src/grammar_tester/grammartester.py
  src/grammar_tester/lgapiparser.py
  src/grammar_tester/lginprocparser.py
  src/grammar_tester/lgmisc.py
  src/grammar_tester/optconst.py
  src/grammar_tester/parsestat.py
  src/grammar_tester/parsevaluate.py
  src/grammar_tester/psparse.py
  src/grammar_tester/textfiledashb.py
  src/link_grammar/grammar-test.py
  src/samples/notebooks/grammar-tester-use-case.ipynb
  tests/test-data/config/AGI-2018-no-dashboard.json
  tests/test-data/corpora/poc-english/poc_english.txt
  tests/test-data/corpora/poc-english/poc_english_noamb_parses_lg.txt
  tests/test-data/corpora/poc-english/poc_english_parses_lg.txt
  tests/test_evaluate.py
  tests/test_grammartester.py
  tests/test_inprocparser.py
  tests/test_lgapiparser.py
  tests/test_lginprocparser.py
  tests/test_parsestat.py
  tests/test_psparse.py
  tests/test_textfiledashb.py
Labels: enhancement

#48 word_senser uses letters to tag senses
  src/disambiguate-pre/annotate_corpora.jl
Labels: enhancement

#49 Parse eval positions
  src/parse_evaluator/parse_evaluator.py
Labels: bug, enhancement

#51 renamed disambiguate-pre to word_senser
  src/word_senser/README.md
  src/word_senser/annotate_corpora.jl
  src/word_senser/annotate_corpora.sh
  src/word_senser/evaluate_WSD.py
  src/word_senser/output_senses.jl
  src/word_senser/output_senses.sh
  src/word_senser/train_multiple_adagram.sh
Labels: enhancement

#52 Change tags for AdaGram model output
  src/word_senser/output_senses.jl
Labels: enhancement

#53 Parse evaluate measures
  src/word_senser/evaluate_WSD.py
Labels: bug

#61 Improve annotate
  src/word_senser/annotate_corpora.sh
  src/word_senser/annotate_corpus.jl
  src/word_senser/annotate_corpus.sh
Labels: enhancement

#63 Fix pearson naming
  src/common/pearson_coeff.py
Labels: enhancement

#64 in WSD, removed double compute_metrics
  src/word_senser/evaluate_WSD.py
Labels: bug

#65 Fixed installing instructions
  README.md
Labels: bug

#69 Square bracket filterring in .ull input
  src/grammar_tester/lginprocparser.py
  src/grammar_tester/psparse.py
  tests/test_psparse.py
Labels: enhancement

#71 Grammar Learner baseline tests with GC, CDS, POC corpora
  data/POC-English-Amb/LG-ANY-all-parses/poc-english_ex-parses-allLG.txt
  data/POC-English-Amb/LG-English/poc-english_ex-parses-silver.txt
  data/POC-English-Amb/LG_English/poc-english_ex-parses-silver.txt
  data/POC-English-Amb/MST-fixed-manually/poc-english_ex-parses-gold.txt
  data/POC-English-Amb/R=6-Weight=1-mst-weight=+1:R/poc-english_ex-parses-win6-mdist.txt
  data/POC-English-Amb/R=6-Weight=6:R-mst-weight=+1:R/poc-english_ex-parses-win6-omdist.txt
  data/POC-English-Amb/poc_english.txt
  data/POC-English-disAmb/LG-ANY-all-parses/EnglishPOC_disamb-parses-lgAll_mdist.txt
  data/POC-English-disAmb/R=6-Weight=1-mst-weight=+1:R/EnglishPOC_disamb-parses-win6-mdist.txt
  data/POC-English-disAmb/R=6-Weight=6:R-mst-weight=+1:R/EnglishPOC_disamb-parses-win6-omdist.txt
  data/POC-Turtle/LG-ANY-all-parses/poc-turtle-parses-allLG.txt
  data/POC-Turtle/LG_ANY_all_parses/poc-turtle-parses-allLG.txt
  data/POC-Turtle/MST-fixed-manually/poc-turtle-parses-gold.txt
  data/POC-Turtle/R=6-Weight=1-no-mst-weighting/poc-english-parses-win6.txt
  data/POC-Turtle/R=6-Weight=6:R-mst-weight=+1:R/poc-english-parses-win6-omdist.txt
  data/POC-Turtle/R=6_Weight=6:R/poc-turtle-parses-window6-distance.txt
  data/POC-Turtle/updated_2018-07-20_files_dated_2018-05-05.txt
  data/POC_English/poc_english_corpus.txt
  data/poc_english_noamb_parse_ideal/poc_english_noamb_parse_ideal.txt
  notebooks/Child-Directed-Speech-2018-07-20.ipynb
  notebooks/Gutenberg-Children-Books-DRK-2018-07-19.ipynb
  notebooks/POC-English-Amb+disAmb-2018-07-20.ipynb
  notebooks/POC-Turtle-2018-07-20.ipynb
  src/utl/pqa_table.py
Labels: wontfix

#72 Parse counter
  src/common/freq_table.sh
  src/common/parse_counter.sh
Labels: enhancement

#73 Implement fscore
  src/word_senser/evaluate_WSD.py
Labels: enhancement

#74 Update POC-Turtle corpus baseline tests
  .gitignore
  data/POC-English-NoAmb/poc_english_noamb_corpus.txt
  data/POC-Turtle/R=6-Weight=1-no-mst-weighting/poc-english-parses-win6.txt
  data/POC-Turtle/R=6-Weight=1-no-mst-weighting/poc-turtle-parses-win6.txt
  data/POC-Turtle/R=6-Weight=6:R-mst-weight=+1:R/poc-english-parses-win6-omdist.txt
  data/POC-Turtle/R=6-Weight=6:R-mst-weight=+1:R/poc-turtle-parses-win6-omdist.txt
  data/poc-english_noCaps-parses-window30-distance-fmi.txt
  data/poc-turtle-opencog-mst-parses.txt
  data/poc_english.txt
  data/poc_english_noamb.txt
  notebooks/POC-English-Amb+disAmb-2018-07-18-multi.ipynb
  notebooks/POC-Turtle-2018-07-20.ipynb
  notebooks/POC-Turtle-2018-07-23.ipynb
  src/utl/pqa_table.py
  tests/test-data/corpora/poc-english/poc_english.txt
  tests/test-data/parses/poc-turtle-mst/poc-turtle-opencog-mst-parses.txt
Labels: enhancement

#75 unified output_model and output_senses
  src/word_senser/output_model.jl
  src/word_senser/output_model.sh
  src/word_senser/output_senses.jl
Labels: enhancement

#77 Add Link Grammar Checker Web UI stuff
  src/web/html/check.html
  src/web/html/check/index.html
  src/web/html/graph.html
  src/web/html/index.html
  src/web/html/test/nlp/poc-english_5C_2018-06-06_0004.4.0.dict.txt
Labels: enhancement

#78 Weighted fscore
  src/word_senser/evaluate_WSD.py
Labels: enhancement

#81 Output overdisamb
  src/word_senser/evaluate_WSD.py
Labels: enhancement

#83 Parse evaluator fscore
  src/parse_evaluator/parse_evaluator.py
Labels: enhancement
