Repository singnet/language-learning, pull requests merged in 2018-10, with the labels that each got.

#113 Update .dict format and tests to Link Grammar 5.5.1
  conda-env-ull-cli-spec.txt
  conda-env-ull-cli.yml
  conda-env-ull-dev-spec.txt
  conda-env-ull-old.yml
  conda-env-ull-spec.txt
  environment.yml
  notebooks/POC-English-NoAmb-2018-09-26.ipynb
  notebooks_/POC-English-NoAmb-2018-09-29_.ipynb
  notebooks_/POC-English-NoAmb-2018-10-03_.ipynb
  notebooks_/POC-English-NoAmb-809-26-multi_.ipynb
  notebooks_/POC-English-NoAmb-80926_.ipynb
  notebooks_/README.md
  src/grammar_learner/write_files.py
  src/grammar_learner_/README.md
  tests/data/POC-Turtle/generalized_categories/dict_6C_2018-10-03_0006.4.0.dict
  tests/data/POC-Turtle/generalized_categories_and_rules/dict_6C_2018-10-03_0006.4.0.dict
  tests/data/POC-Turtle/generalized_rules/dict_6C_2018-10-03_0006.4.0.dict
  tests/data/POC-Turtle/no_generalization/dict_8C_2018-10-03_0006.4.0.dict
  tests/test_grammar_learner.py
Labels: bug

#114 Test updated Grammar Learner with POC English corpora (/notebooks_)
  data/CDS-caps-br-text+brent9mos/R=6-Weight=6:R-mst-weight=+1:R/br-text-parses-win6-omdist.ull
  data/CDS-caps-br-text+brent9mos/R=6-Weight=6:R-mst-weight=+1:R/brent9mos-parses-win6-omdist.ull
  data/POC-English-Amb/LG-English/poc_english-LG-silver.txt.ull
  data/POC-English-disAmb/LG-ANY-all-parses-agm-100/EnglishPOC.txtadagram_EnglishPOC.txt_WO8D300E1000000M5A1.3W3_disamb.ull
  data/POC-English-disAmb/LG-ANY-all-parses-agm-opt/EnglishPOC.txtadagramWO8D50E1000000M1A1.3W3R0_disamb_lgAll.ull
  data/POC-English-disAmb/LG-ANY-all-parses/EnglishPOC_disamb-parses-lgAll.ull
  data/POC-English-disAmb/R=6-Weight=1-mst-weight=+1:R-agm-100/EnglishPOC.txtadagram_EnglishPOC.txt_WO8D300E1000000M5A1.3W3_disamb.ull
  data/POC-English-disAmb/R=6-Weight=1-mst-weight=+1:R-agm-opt/EnglishPOC.txtadagramWO8D50E1000000M1A1.3W3R0_disamb_win6_mdist.ull
  data/POC-English-disAmb/R=6-Weight=1-mst-weight=+1:R/EnglishPOC_disamb-parses-win6-mdist.ull
  data/POC-English-disAmb/R=6-Weight=6:R-mst-weight=+1:R-agm-100/EnglishPOC.txtadagram_EnglishPOC.txt_WO8D300E1000000M5A1.3W3_disamb.ull
  data/POC-English-disAmb/R=6-Weight=6:R-mst-weight=+1:R-agm-opt/EnglishPOC.txtadagramWO8D50E1000000M1A1.3W3R0_disamb_win6_omdist.ull
  data/POC-English-disAmb/R=6-Weight=6:R-mst-weight=+1:R/EnglishPOC_disamb-parses-win6-omdist.ull
  notebooks_/POC-English-Amb-2018-10-04.ipynb
  notebooks_/POC-English-NoAmb-2018-10-04.ipynb
Labels: test

#115 Random baseline
  setup.py
  src/cli_scripts/parse-evaluator
  src/parse_evaluator/__init__.py
  src/parse_evaluator/parse_evaluator.py
Labels: enhancement

#116 Implement sparse vector space and agglomerative clustering.
  notebooks_/Agglomerative_Clustering_2018-10-12_.ipynb
  src/grammar_learner/category_learner.py
  src/grammar_learner/grammar_inducer.py
  src/grammar_learner_/agglomerative_clustering_.py
  src/grammar_learner_/sparse_word_space_.py
Labels: enhancement

#119 Update baseline tests: Link Grammar 5.4.4, updated test_grammar with F1.
  notebooks/Child-Directed-Speech-2018-10-18.ipynb
  notebooks/POC-English-2018-10-18.ipynb
  notebooks/POC-English-2018-10-19.ipynb
  notebooks/POC-English-NoAmb-2018-10-19.ipynb
  notebooks/POC-Turtle-2018-10-18-multi.ipynb
  notebooks/POC-Turtle-2018-10-18.ipynb
  notebooks/POC-Turtle-2018-10-19-multi-10x.ipynb
  notebooks/POC-Turtle-2018-10-19.ipynb
  notebooks_/POC-English-Amb-2018-10-04.ipynb
  notebooks_/POC-English-NoAmb-2018-10-03_.ipynb
  notebooks_/POC-English-NoAmb-2018-10-04.ipynb
  src/grammar_learner/README.md
  src/grammar_learner/category_learner.py
  src/grammar_learner/pqa_table.py
  src/grammar_learner_/pqa_table_.py
  tests/test_grammar_learner.py
Labels: enhancement, test

#120 Fix grammar induction; category id's in rules generalization, clustering
  notebooks/Child-Directed-Speech-2018-10-18.ipynb
  notebooks/Child-Directed-Speech-2018-10-19.ipynb
  notebooks/POC-English-2018-10-18.ipynb
  notebooks/POC-English-2018-10-19.ipynb
  notebooks/POC-English-NoAmb-2018-10-19.ipynb
  notebooks/POC-Turtle-2018-10-18-multi.ipynb
  notebooks/POC-Turtle-2018-10-18.ipynb
  notebooks/POC-Turtle-2018-10-19-multi-10x.ipynb
  notebooks/POC-Turtle-2018-10-19.ipynb
  notebooks/README.md
  notebooks_/Agglomerative_Clustering_2018-10-12_.ipynb
  src/grammar_learner/category_learner.py
  src/grammar_learner/clustering.py
  src/grammar_learner/generalization.py
  src/grammar_learner/grammar_inducer.py
  src/grammar_learner/pqa_table.py
  tests/test_grammar_learner.py
Labels: bug, enhancement, test

#121 Grammar Learner 0.6 baseline tests after grammar induction fixes, Link Grammar 5.4.4.
  notebooks/Child-Directed-Speech-2018-09-11.ipynb
  notebooks/Child-Directed-Speech-2018-10-18.ipynb
  notebooks/Child-Directed-Speech-2018-10-21.ipynb
  notebooks/POC-English-2018-10-18.ipynb
  notebooks/POC-English-2018-10-19.ipynb
  notebooks/POC-English-2018-10-21.ipynb
  notebooks/POC-English-Amb-2018-09-11-multi.ipynb
  notebooks/POC-English-Amb-2018-09-11.ipynb
  notebooks/POC-Turtle-2018-09-11.ipynb
  notebooks/POC-Turtle-2018-10-18-multi.ipynb
  notebooks/POC-Turtle-2018-10-19-multi-10x.ipynb
  notebooks/POC-Turtle-2018-10-21.ipynb
  src/grammar_learner/clustering.py
  src/grammar_learner_/category_learner_.py
  src/grammar_learner_/clustering_.py
  tests/data/POC-Turtle/no_generalization/dict_8C_2018-10-21_0006.4.0.dict
  tests/test_grammar_learner.py
Labels: bug, enhancement, test

#123 Update Grammar Learner README: agglomerative clustering **kwargs
  README.md
  src/grammar_learner/README.md
Labels: enhancement
