Repository singnet/language-learning, pull requests merged in 2019-06, with the labels that each got.

#223 Minor documentation additions
  src/cli_scripts/parse-evaluator
  src/common/dirhelper.py
  src/grammar_tester/parsevaluate.py
Labels: enhancement

#227 parse-evaluator fixes for issue #226
  src/cli_scripts/parse-evaluator
  src/common/optconst.py
  src/grammar_tester/artificialparser.py
  src/grammar_tester/lgapiparser.py
  src/grammar_tester/lginprocparser.py
  src/grammar_tester/parsevaluate.py
  tests/test_lginprocparser.py
  tests/test_parsevaluate.py
Labels: bug, enhancement

#233 GT fixes for proper handling input corpus CR/LFs
  src/common/sedcommands.py
  src/common/sentencecount.py
  src/grammar_tester/lginprocparser.py
  src/grammar_tester/psparse.py
  tests/test_psparse.py
Labels: bug

#236 Documentation fixes
  cli-scripts.md
  pipeline.md
  setup.py
  src/cli_scripts/word-counter
  src/common/sentencecount.py
  src/grammar_tester/lginprocparser.py
  src/link_grammar/dicttools.py
Labels: enhancement

#237 Content words evaluator
  src/cli_scripts/parse-evaluator
  src/parse_evaluator/README.md
  src/parse_evaluator/func_words.txt
  src/parse_evaluator/parse_evaluator.py
Labels: enhancement

#239 Avoid printing empty lines in pre-cleaner
  src/pre_cleaner/pre_cleaner.py
  tests/test-data/pre-cleaner/split-books/pg9212.txt
Labels: bug
