Repository singnet/language-learning, pull requests merged in 2019-04, with the labels that each got.

#192 fixed bug in sequential and random evaluation
  src/parse_evaluator/parse_evaluator.py
Labels: bug

#197 Issue #184 fixes
  cli-scripts.md
  pipeline.md
  setup.py
  src/cli_scripts/grammar-tester
  src/cli_scripts/token-counter
  src/common/__init__.py
  src/common/absclient.py
  src/common/optconst.py
  src/common/sedcommands.py
  src/common/sentencecount.py
  src/common/textprogress.py
  src/common/tokencount.py
  src/grammar_learner/pqa_table.py
  src/grammar_tester/__init__.py
  src/grammar_tester/grammartester.py
  src/grammar_tester/lgapiparser.py
  src/grammar_tester/lginprocparser.py
  src/grammar_tester/lgmisc.py
  src/grammar_tester/lgpcommands.py
  src/grammar_tester/parsestat.py
  src/grammar_tester/psparse.py
  src/parse_evaluator/parse_evaluator.py
  src/text_parser/__init__.py
  tests/old_test_inprocparser.py
  tests/test-data/corpora/poc-turtle/poc-turtle-dot-separated.txt
  tests/test-data/sentence-skip-test/issue-184.txt
  tests/test_grammartester.py
  tests/test_grammartester_input.py
  tests/test_lgapiparser.py
  tests/test_lginprocparser.py
  tests/test_psparse.py
  tests/test_tokencount.py
Labels: enhancement

#199 Filtering parses to get test sets with high frequency words
  notebooks/GCB_test_sets_with_MWC=[11...51]_2019-04-08.ipynb
  src/grammar_learner/utl.py
Labels: enhancement

#202 included printing of sequential/random parses in evaluator
  src/parse_evaluator/parse_evaluator.py
Labels: enhancement

#203 Compare tokenization
  src/cli_scripts/parse-evaluator
  src/parse_evaluator/parse_evaluator.py
Labels: enhancement

#204 Added script to obtain sentences only from parse files
  src/common/sentence_getter.sh
Labels: enhancement

#201 Optional WSD, parses filtering, alternative learned grammar assessment
  notebooks/Alternative_F1_for_ALE_ILE clustering_2019-04-12.ipynb
  notebooks/Parses_filtering_issue_2019-04-10_.ipynb
  notebooks/WSD_option_tests_2019-04-09_.ipynb
  src/grammar_learner/README.md
  src/grammar_learner/grammar_checker.py
  src/grammar_learner/incremental_clustering.py
  src/grammar_learner/learner.py
  src/grammar_learner/pparser.py
  src/grammar_learner/pqa_table.py
  src/grammar_learner/preprocessing.py
  src/grammar_learner/write_files.py
Labels: bug, enhancement

#205 Issue #184 and more
  cli-scripts.md
  pipeline.md
  setup.py
  src/cli_scripts/sentence-counter
  src/common/sedcommands.py
  src/common/sentencecount.py
  src/common/tokencount.py
  src/grammar_tester/grammartester.py
  src/grammar_tester/lginprocparser.py
  src/grammar_tester/parsestat.py
  src/grammar_tester/psparse.py
  src/observer/lgobserver.py
  src/observer/wordpairs.py
  src/pipeline/__init__.py
  src/pipeline/pipelineexceptions.py
  src/pipeline/pipelinetree.py
  tests/test-data/corpora/poc-english/poc_english_noamb_parses_ideal_1s_2.txt.stat
  tests/test-data/regex-test/regex-test-result-lcase.txt
  tests/test-data/regex-test/regex-test-result.txt
  tests/test-data/regex-test/regex-test.txt.ull
  tests/test-data/regex-test/ull-new.txt.ull
  tests/test-data/second-linkage-test/GCB-NQ.txt
  tests/test-data/second-linkage-test/GCB-NQ.txt.raw
  tests/test_lgapiparser.py
  tests/test_lginprocparser.py
  tests/test_parsestat.py
  tests/test_psparse.py
  tests/test_sedcommands.py
Labels: bug, enhancement

#208 Pipeline exception handling improvements
  src/cli_scripts/token-counter
  src/cli_scripts/ull-cli
  src/pipeline/pipelineexceptions.py
  src/pipeline/pipelinetree.py
  src/pipeline/pipelinetreenode.py
Labels: enhancement

#206 Fix MWC filtering, explore ILE (poor) clusterization with MWC > 1
  notebooks/ILE-clustering-research-GCB-LG-E-noQuotes-2019-04-19.ipynb
  src/grammar_learner/category_learner.py
  src/grammar_learner/grammar_inducer.py
  src/grammar_learner/incremental_clustering.py
  src/grammar_learner/learner.py
  src/grammar_learner/pparser.py
  src/grammar_learner/preprocessing.py
  src/grammar_learner/sparse_word_space.py
  src/grammar_learner/write_files.py
Labels: bug, enhancement, test

#211 Fix case of requested number of clusters > number of words
  notebooks/issue_209_CDS-ALE_ILE-LG-English-clean-2019-04-25.ipynb
  notebooks/issue_209_cALEd-500-GCB-sequential_parses-MWC=1-2019-04-24.ipynb
  src/grammar_learner/pqa_table.py
  src/grammar_learner/skl_clustering.py
Labels: bug

#212 Raise ValueError in case of empty dataset due to wrong filtering parameters
  src/grammar_learner/learner.py
Labels: bug

#213 Pipeline improvements
  README.md
  src/cli_scripts/ull-cli
  src/common/parsemetrics.py
  src/grammar_tester/lginprocparser.py
  src/pipeline/pipelineexceptions.py
  src/pipeline/pipelinetree.py
  src/pipeline/pipelinetreenode.py
  src/pipeline/varhelper.py
  tests/test_pipelinetree.py
  tests/test_varhelper.py
Labels: bug, enhancement
