Repository singnet/language-learning, pull requests merged in 2019-01, with the labels that each got.

#157 Resolve GL crash when optimal number of clusters cannot be found.
  README.md
  notebooks/Child-Directed-Speech-2019-01-03.ipynb
  notebooks/Gutenberg-Children-Books-LG-E-clean-MWC=2-2019-01-03.ipynb
  pipeline/README.md
  pipeline/issue_01.json
  src/grammar_learner/clustering.py
  src/grammar_learner/utl.py
Labels: bug

#158 Resolve minor issues, use Link Grammar 5.5.1 only, clean code.
  src/grammar_learner/skl_clustering.py
  src/grammar_learner/utl.py
  src/grammar_learner/write_files.py
Labels: enhancement

#159 Small pipeline bug fixes
  src/cli_scripts/ull-cli
  src/common/parsemetrics.py
  src/grammar_tester/grammartester.py
  src/grammar_tester/lginprocparser.py
  src/grammar_tester/optconst.py
  src/pipeline/pipelinetree.py
  src/pipeline/pipelinetreenode.py
  tests/test_lgapiparser.py
Labels: bug

#160 Grammar Tester CLI tests: check 2018 results reproducibility
  pipeline/Check-GCB-2018-12-14-500c-mwc=1+.json
  pipeline/Check-GCB-2018-12-14-500c-mwc=1.json
  pipeline/GT-CDS-LG-E-551-cDRKc-90119.json
  pipeline/GT-GCB-2018-12-14-500c-mwc=1.json
  pipeline/README.md
  pipeline/ppln.py
  pipeline/tstr.py
Labels: test

#162 Add Link Grammar 5.4.4 & 5.5.1 options to .dict file, tag Grammar_Learner_0.7.1.
  pipeline/CDS-LG-E-Clean-11-50.json
  pipeline/README.md
  pipeline/ppln.py
  src/grammar_learner/write_files.py
Labels: enhancement

#163 CLI category_tagger utility prototype 0.0.1
  data/CDS/LG-E-551/br-text.txt_U.ull
  data/CDS/LG-E-551/brent9mos.txt_U.ull
  data/CDS/LG-E-clean/CDS-LG-English-clean.ull
  data/POC-English-Amb/LG-E-551/EnglishPOC.txt.ull
  pipeline/CT-CDS-LG-E-551.json
  pipeline/CT-CDS-LG-E-clean.json
  pipeline/README.md
  pipeline/category_tagger
  src/grammar_learner/incremental_clustering.py
  src/grammar_learner/read_files.py
Labels: enhancement
